apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-metrics-exporter
subjects:
  - kind: ServiceAccount
    name: cloud-metrics-exporter
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-metrics-exporter
