- job_name: cloud-metrics-exporter
  kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
          - monitoring
  relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      action: keep
      regex: cloud-metrics-exporter
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      action: keep
      regex: metrics
    - target_label: __metrics_path__
      action: replace
      replacement: /metrics
